section_titles_tree = {"accomplishments": ["CONFERENCE PRESENTATIONS",
                     "Conventions",
                     "CONVENTIONS",
                     "Current Research Interests",
                     "CURRENT RESEARCH INTERESTS",
                     "Dissertation",
                     "DISSERTATION",
                     "Dissertations",
                     "DISSERTATIONS",
                     "Exhibits",
                     "EXHIBITS",
                     "Licenses",
                     "LICENSES",
                     "Papers",
                     "PAPERS",
                     "Presentations",
                     "PRESENTATIONS",
                     "Professional Publications",
                     "PROFESSIONAL PUBLICATIONS",
                     "Publications",
                     "PUBLICATIONS",
                     "Research",
                     "RESEARCH",
                     "Research Grants",
                     "RESEARCH GRANTS",
                     "Research Interests",
                     "RESEARCH INTERESTS",
                     "Research Projects",
                     "RESEARCH PROJECTS",
                     "Thesis / Theses",
                     "THESIS / THESES"],
 "awards": ["ACADEMIC HONORS",
            "Accolades",
            "ACCOLADES",
            "Accomplishments",
            "ACCOMPLISHMENTS",
            "Achievements",
            "ACHIEVEMENTS",
            "Activities and Honors",
            "ACTIVITIES AND HONORS",
            "Awards",
            "AWARDS",
            "Distinctions",
            "DISTINCTIONS",
            "Endorsements",
            "ENDORSEMENTS",
            "Fellowship",
            "FELLOWSHIP",
            "Fellowships",
            "FELLOWSHIPS",
            "Honors",
            "HONORS",
            "Scholarship",
            "SCHOLARSHIP",
            "Scholarships",
            "SCHOLARSHIPS"],
 "credibility": ["PORTFOLIO",
                 "Recommendations",
                 "RECOMMENDATIONS",
                 "References",
                 "REFERENCES",
                 "Social Media Profiles",
                 "SOCIAL MEDIA PROFILES",
                 "Social Profiles",
                 "SOCIAL PROFILES",
                 "Testimonials",
                 "TESTIMONIALS",
                 "Web Portfolio",
                 "WEB PORTFOLIO",
                 "Websites",
                 "WEBSITES"],
 "education_and_training": ["Academic Background",
                            "ACADEMIC EXPERIENCE",
                            "Academic Experience",
                            "ACADEMIC TRAINING",
                            "Academic Training",
                            "APPRENTICESHIPS",
                            "Apprenticeships",
                            "CERTIFICATION",
                            "Certification",
                            "CERTIFICATIONS",
                            "Certifications",
                            "COLLEGE ACTIVITIES",
                            "College Activities",
                            "COURSE PROJECT EXPERIENCE",
                            "Course Project Experience",
                            "COURSES",
                            "Courses",
                            "EDUCATION",
                            "Education",
                            "EDUCATION AND TRAINING",
                            "Education and Training",
                            "EDUCATIONAL BACKGROUND",
                            "Educational Background",
                            "EDUCATIONAL QUALIFICATIONS",
                            "Educational Qualifications",
                            "EDUCATIONAL TRAINING",
                            "Educational Training",
                            "INTERNSHIP EXPERIENCE",
                            "Internship Experience",
                            "INTERNSHIPS",
                            "Internships",
                            "Patent",
                            "PATENT",
                            "Patents",
                            "PATENTS",
                            "Professional Training",
                            "PROFESSIONAL TRAINING",
                            "Programs",
                            "PROGRAMS",
                            "RELATED COURSE PROJECTS",
                            "Related Course Projects",
                            "RELATED COURSES",
                            "Related Courses",
                            "Special Training",
                            "SPECIAL TRAINING",
                            "Study",
                            "STUDY",
                            "Training",
                            "TRAINING",
                            "Workshop",
                            "WORKSHOP",
                            "Workshops",
                            "WORKSHOPS"],
 "extracurricular": ["ACTIVITIES",
                     "Activities and Honors",
                     "ACTIVITIES AND HONORS",
                     "Affiliations",
                     "AFFILIATIONS",
                     "Associations",
                     "ASSOCIATIONS",
                     "Athletic Involvement",
                     "ATHLETIC INVOLVEMENT",
                     "Civic Activities",
                     "CIVIC ACTIVITIES",
                     "Community Involvement",
                     "COMMUNITY INVOLVEMENT",
                     "Extra-Curricular Activities",
                     "EXTRA-CURRICULAR ACTIVITIES",
                     "Honors",
                     "HONORS",
                     "Memberships",
                     "MEMBERSHIPS",
                     "Professional Activities",
                     "PROFESSIONAL ACTIVITIES",
                     "Professional Affiliations",
                     "PROFESSIONAL AFFILIATIONS",
                     "Professional Associations",
                     "PROFESSIONAL ASSOCIATIONS",
                     "Professional Memberships",
                     "PROFESSIONAL MEMBERSHIPS",
                     "Volunteer Experience",
                     "VOLUNTEER EXPERIENCE",
                     "Volunteer Work",
                     "VOLUNTEER WORK"],
 "misc": ["Hobbies",
          "INTERESTS",
          "Interests",
          "MISCELLANEOUS",
          "Miscellaneous",
          "PERSONAL INTERESTS",
          "Personal Interests",
          "Personal Strength",
          "PERSONAL STRENGTH",
          "Personal Strengths",
          "PERSONAL STRENGTHs",
          "STRENGTH",
          "Strength",
          "STRENGTHS",
          "Strengths"],
 "skills": ["ABILITIES",
            "Areas of Experience",
            "AREAS OF EXPERIENCE",
            "Areas of Expertise",
            "AREAS OF EXPERTISE",
            "Areas of Knowledge",
            "AREAS OF KNOWLEDGE",
            "Career Related Skills",
            "CAREER RELATED SKILLS",
            "Computer Knowledge",
            "COMPUTER KNOWLEDGE",
            "Computer Skills",
            "COMPUTER SKILLS",
            "Credentials",
            "CREDENTIALS",
            "Expertise",
            "EXPERTISE",
            "Language Competencies and Skills",
            "LANGUAGE COMPETENCIES AND SKILLS",
            "Languages",
            "LANGUAGES",
            "Professional Skills",
            "PROFESSIONAL SKILLS",
            "Proficiencies",
            "PROFICIENCIES",
            "Programming Languages",
            "PROGRAMMING LANGUAGES",
            "Qualifications",
            "QUALIFICATIONS",
            "Skills",
            "SKILLS",
            "Specialized Skills",
            "SPECIALIZED SKILLS",
            "Technical Experience",
            "TECHNICAL EXPERIENCE",
            "Technical Skills",
            "TECHNICAL SKILLS",
            "Technologies",
            "TECHNOLOGIES"],
 "summary": ["Career Goal",
             "CAREER OBJECTIVE",
             "Career Objective",
             "CAREER SUMMARY",
             "Career Summary",
             "EMPLOYMENT OBJECTIVE",
             "Employment Objective",
             "HIGHLIGHTS",
             "Highlights",
             "JOB OBJECTIVE",
             "Job Objective",
             "OBJECTIVE",
             "Objective",
             "PROFESSIONAL OBJECTIVE",
             "Professional Objective",
             "Professional Profile",
             "PROFESSIONAL PROFILE",
             "Professional Summary",
             "PROFESSIONAL SUMMARY",
             "PROFILE",
             "Profile",
             "SUMMARY",
             "Summary",
             "SUMMARY OF QUALIFICATIONS",
             "Summary of Qualifications",
             "SUMMARY STATEMENT",
             "Summary Statement",
             "TECHNICAL SUMMARY",
             "Technical Summary"],
 "work_experience": ["Additional Experience",
                     "ARMY EXPERIENCE",
                     "Army Experience",
                     "CAREER RELATED EXPERIENCE",
                     "Career Related Experience",
                     "EMPLOYMENT HISTORY",
                     "Employment History",
                     "EXPERIENCE",
                     "Experience",
                     "FREELANCE",
                     "Freelance",
                     "FREELANCE EXPERIENCE",
                     "Freelance Experience",
                     "MILITARY BACKGROUND",
                     "Military Background",
                     "MILITARY EXPERIENCE",
                     "Military Experience",
                     "PROFESSIONAL BACKGROUND",
                     "Professional Background",
                     "PROFESSIONAL EXPERIENCE",
                     "Professional Experience",
                     "Project",
                     "PROJECT",
                     "Projects",
                     "PROJECTS",
                     "Related Experience",
                     "RELATED EXPERIENCE",
                     "WORK EXPERIENCE",
                     "Work Experience",
                     "Work History",
                     "WORK HISTORY"]}
